name: Run Daily Script

on:
  schedule:
    - cron: "45 3 * * *"  # Runs every day at 9:15 AM IST (3:45 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Write Google Sheets credentials from secret
      - name: Write Google Sheets credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > gen-lang-client-0821497990-b7d00535dc2e.json

      # Step 5: Configure other secrets (e.g., API keys, credentials)
      - name: Configure secrets
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "TOTP_TOKEN=${{ secrets.TOTP_TOKEN }}" >> $GITHUB_ENV

      # Step 6: Run the script
      - name: Run script
        run: |
          python optionchain.py
